# Generated by Django 5.1.4 on 2025-03-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmeta',
            name='end_repeat',
        ),
        migrations.AddField(
            model_name='event',
            name='end_repeat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
