# Generated by Django 5.1.4 on 2025-03-06 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_author_alter_event_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmeta',
            name='start_repeat',
        ),
        migrations.AddField(
            model_name='eventmeta',
            name='byweekday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventmeta',
            name='daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmeta',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmeta',
            name='weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmeta',
            name='yearly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventmeta',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventmeta',
            name='interval',
            field=models.IntegerField(default=1),
        ),
    ]
