# Generated by Django 5.1.4 on 2025-03-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventmeta_start_repeat_eventmeta_byweekday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmeta',
            name='daily',
        ),
        migrations.RemoveField(
            model_name='eventmeta',
            name='monthly',
        ),
        migrations.RemoveField(
            model_name='eventmeta',
            name='weekly',
        ),
        migrations.RemoveField(
            model_name='eventmeta',
            name='yearly',
        ),
        migrations.AddField(
            model_name='eventmeta',
            name='bymonthday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventmeta',
            name='freq',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='WEEKLY', max_length=7),
            preserve_default=False,
        ),
    ]
