# Generated by Django 5.1.4 on 2025-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_eventmeta_daily_remove_eventmeta_monthly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmeta',
            name='freq',
            field=models.CharField(choices=[(3, 'Daily'), (2, 'Weekly'), (1, 'Monthly'), (0, 'Yearly')], max_length=7),
        ),
    ]
