# Generated by Django 5.1.4 on 2025-03-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventmeta_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmeta',
            name='bymonth',
            field=models.IntegerField(blank=True, choices=[(0, None), (1, 'January'), (2, 'Fabruary'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='eventmeta',
            name='byweekno',
            field=models.IntegerField(blank=True, choices=[(0, None), (1, 'January'), (2, 'Fabruary'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AlterField(
            model_name='eventmeta',
            name='freq',
            field=models.IntegerField(choices=[(3, 'Daily'), (2, 'Weekly'), (1, 'Monthly'), (0, 'Yearly')]),
        ),
    ]
