# Generated by Django 5.1.4 on 2025-05-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventmeta_byweekno_canceledevent'),
        ('users', '0011_userprofile_premium_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(related_name='events', to='users.groupuser'),
        ),
    ]
