# Generated by Django 5.1.4 on 2025-08-23 09:09
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Event_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('groupuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.groupuser')),
            ],
        )
    ]
