# Generated by Django 5.1.4 on 2025-08-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
