# Generated by Django 5.1.4 on 2025-10-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_reminder_1_event_reminder_2'),
        ('users', '0014_group_unique_default_group_per_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Users',
            new_name='EventUser',
        ),
    ]
