# Generated by Django 5.1.4 on 2025-10-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rename_event_users_eventuser'),
        ('users', '0014_group_unique_default_group_per_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventuser',
            table='events_event_users',
        ),
    ]
