# Generated by Django 5.1.4 on 2025-10-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_eventuser_left_alter_event_users_and_more'),
        ('users', '0014_group_unique_default_group_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='eventuser',
            unique_together={('event', 'groupuser')},
        ),
    ]
