# Generated by Django 5.1.4 on 2025-10-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_rename_group_user_eventuser_groupuser_eventuser_left_and_more'),
        ('users', '0014_group_unique_default_group_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='new_users',
            field=models.ManyToManyField(related_name='events_new', through='events.EventUser', to='users.groupuser'),
        ),
        migrations.AlterModelTable(
            name='eventuser',
            table='events_event_users_new',
        ),
    ]
