# Generated by Django 5.1.4 on 2025-10-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_new_users_alter_eventuser_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # В БД ничего не меняем
            state_operations=[
                migrations.RemoveField(
                    model_name='event',
                    name='users',
                ),
            ]
        )
    ]
