# Generated by Django 5.1.4 on 2025-10-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_event_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='new_users',
            new_name='users',
        ),
    ]
