# Generated by Django 5.1.4 on 2025-10-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_rename_new_users_event_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventuser',
            table='events_event_users',
        ),
    ]
