# Generated by Django 5.1.4 on 2026-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_eventuser_table'),
        ('users', '0014_group_unique_default_group_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(related_name='events', through='events.EventUser', to='users.groupuser'),
        ),
    ]
