# Generated by Django 5.1.4 on 2026-03-30 21:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название списка')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создан')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Когда изменен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='shared_lists', to='users.groupuser', verbose_name='С кем поделились')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создан')),
                ('checked', models.BooleanField(default=False, verbose_name='Отмечен или нет')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='notes.list')),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок заметки')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создана')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Когда изменена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='shared_notes', to='users.groupuser', verbose_name='С кем поделились')),
            ],
            options={
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('default', models.BooleanField(default=False, verbose_name='Общая')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Категория рецептов',
                'verbose_name_plural': 'Категории рецептов',
                'ordering': ['default'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Фото')),
                ('default', models.BooleanField(default=False, verbose_name='Общий')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создан')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Когда изменен')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на рецепт')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='В избранном')),
                ('users', models.ManyToManyField(blank=True, related_name='shared_recipes', to='users.groupuser', verbose_name='С кем поделились')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='notes.recipecategory', verbose_name='Категория рецептов')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата в формате "2025-09-14"')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время в формате "18:30:00"')),
                ('important', models.BooleanField(default=False, verbose_name='Важная или нет')),
                ('done', models.BooleanField(default=False, verbose_name='Сделана или нет')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создана')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Когда изменена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='shared_tasks', to='users.groupuser', verbose_name='С кем поделились')),
            ],
            options={
                'ordering': ['date', '-important', 'time'],
            },
        ),
    ]
