# Generated by Django 5.1.4 on 2025-10-05 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date', '-important', 'time']},
        ),
        migrations.AlterField(
            model_name='note',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создана'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(verbose_name='Текст заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда изменена'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создана'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата в формате "2025-09-14"'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Сделана или нет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важная или нет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='Текст задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время в формате "18:30:00"'),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда изменена'),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название списка')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создан')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Когда изменен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создан')),
                ('checked', models.BooleanField(default=False, verbose_name='Отмечен или нет')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.list')),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
    ]
