# Generated by Django 5.1.4 on 2025-10-30 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_task_options_alter_note_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='notes.list'),
        ),
    ]
