# Generated by Django 5.1.4 on 2026-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_listitem_list'),
        ('users', '0014_group_unique_default_group_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shared_notes', to='users.groupuser', verbose_name='С кем поделились'),
        ),
    ]
