# Generated by Django 5.1.4 on 2026-01-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_users'),
        ('users', '0014_group_unique_default_group_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shared_lists', to='users.groupuser', verbose_name='С кем поделились'),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shared_tasks', to='users.groupuser', verbose_name='С кем поделились'),
        ),
    ]
