# Generated by Django 5.1.4 on 2026-02-22 16:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_list_users_task_users'),
        ('users', '0015_userprofile_telegram_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('default', models.BooleanField(default=False, verbose_name='Общая')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='shared_categories', to='users.groupuser', verbose_name='С кем поделились')),
            ],
            options={
                'ordering': ['default'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Фото')),
                ('default', models.BooleanField(default=False, verbose_name='Общий')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создан')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Когда изменен')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='В избранном')),
                ('users', models.ManyToManyField(blank=True, related_name='shared_recipes', to='users.groupuser', verbose_name='С кем поделились')),
                ('category', models.ManyToManyField(blank=True, to='notes.recipecategory', verbose_name='Категория')),
            ],
            options={
                'ordering': ['-update_at'],
            },
        ),
    ]
