# Generated by Django 5.1.4 on 2026-03-05 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_recipecategory_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-update_at'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'ordering': ['default'], 'verbose_name': 'Категория рецептов', 'verbose_name_plural': 'Категории рецептов'},
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='users',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='notes.recipecategory', verbose_name='Категория рецептов'),
        ),
    ]
