# Generated by Django 5.1.4 on 2026-03-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_recipe_options_alter_recipecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
