# Generated by Django 5.1.4 on 2026-03-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_remove_recipe_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_category',
            new_name='category',
        ),
    ]
