# Generated by Django 5.1.4 on 2026-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_rename_recipe_category_recipe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-update_at'], 'verbose_name': 'Список', 'verbose_name_plural': 'Списки'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на рецепт'),
        ),
    ]
