# Generated by Django 5.1.4 on 2026-05-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date', '-important', 'time'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Иконка'),
        ),
    ]
