server {
    server_tokens off;
    listen 80;
    server_name 127.0.0.1 localhost;

    location /.well-known/acme-challenge/ {
        root /var/html/certbot;
    }

    location /static/ {
        root /var/html/;
    }

    location /media/ {
        root /var/html/;
    }

    location / {
        proxy_pass http://planner-back:8000/;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
    }
}