# Generated by Django 5.1.4 on 2025-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_signupcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='admin',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='default group', max_length=100),
            preserve_default=False,
        ),
    ]
