# Generated by Django 5.1.4 on 2025-02-06 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_admin_group_owner_group_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGroup',
            new_name='GroupUser',
        ),
    ]
