# Generated by Django 5.1.4 on 2025-02-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_groupuser_group_alter_groupuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default='blue', max_length=50),
            preserve_default=False,
        ),
    ]
