# Generated by Django 5.1.4 on 2025-02-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
