# Generated by Django 5.1.4 on 2025-02-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='color',
        ),
    ]
