# Generated by Django 5.1.4 on 2025-04-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_groupuser_user_color_alter_groupuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
