# Generated by Django 5.1.4 on 2025-05-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_premium_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
