# Generated by Django 5.1.4 on 2025-10-05 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_groupuser_group_alter_groupuser_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('owner',), name='unique_default_group_per_user'),
        ),
    ]
