# Generated by Django 5.1.4 on 2026-03-05 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userprofile_telegram_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Обращение пользователя')),
                ('file', models.FileField(blank=True, null=True, upload_to='tickets', verbose_name='Приложенный файл')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Ответ поддержки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обращение пользователя',
                'verbose_name_plural': 'Обращения пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
